[build]
  command = "echo 'No build step'"
  publish = "."

[functions]
  directory = "netlify/functions"

[functions.timeout]
  duration = 30

[[headers]]
for = "/*"
  [headers.values]
  X-Frame-Options = "ALLOWALL"
  Content-Security-Policy = "frame-ancestors *;"